package com.wusong.hanukkah.dao.mysql;

import com.wusong.hanukkah.domain.mysql.WusongCourseCode;

public interface WusongCourseCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wusong_course_code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wusong_course_code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    int insert(WusongCourseCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wusong_course_code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    int insertSelective(WusongCourseCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wusong_course_code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    WusongCourseCode selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wusong_course_code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    int updateByPrimaryKeySelective(WusongCourseCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wusong_course_code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    int updateByPrimaryKey(WusongCourseCode record);
}