package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class AdviceApplySupplement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.order_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.advice_apply_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private String adviceApplyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.user_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.content
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.type
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.source
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.create_date
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply_supplement.update_date
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.id
     *
     * @return the value of advice_apply_supplement.id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.id
     *
     * @param id the value for advice_apply_supplement.id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.order_id
     *
     * @return the value of advice_apply_supplement.order_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.order_id
     *
     * @param orderId the value for advice_apply_supplement.order_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.advice_apply_id
     *
     * @return the value of advice_apply_supplement.advice_apply_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public String getAdviceApplyId() {
        return adviceApplyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.advice_apply_id
     *
     * @param adviceApplyId the value for advice_apply_supplement.advice_apply_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setAdviceApplyId(String adviceApplyId) {
        this.adviceApplyId = adviceApplyId == null ? null : adviceApplyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.user_id
     *
     * @return the value of advice_apply_supplement.user_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.user_id
     *
     * @param userId the value for advice_apply_supplement.user_id
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.content
     *
     * @return the value of advice_apply_supplement.content
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.content
     *
     * @param content the value for advice_apply_supplement.content
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.type
     *
     * @return the value of advice_apply_supplement.type
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.type
     *
     * @param type the value for advice_apply_supplement.type
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.source
     *
     * @return the value of advice_apply_supplement.source
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.source
     *
     * @param source the value for advice_apply_supplement.source
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.create_date
     *
     * @return the value of advice_apply_supplement.create_date
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.create_date
     *
     * @param createDate the value for advice_apply_supplement.create_date
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply_supplement.update_date
     *
     * @return the value of advice_apply_supplement.update_date
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply_supplement.update_date
     *
     * @param updateDate the value for advice_apply_supplement.update_date
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}