package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class AdviceOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.order_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.creator_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.province
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.city
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.push_city_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Integer pushCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.question
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String question;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.price
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.order_status
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.pay_state
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Integer payState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_order.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.order_id
     *
     * @return the value of advice_order.order_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.order_id
     *
     * @param orderId the value for advice_order.order_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.creator_id
     *
     * @return the value of advice_order.creator_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.creator_id
     *
     * @param creatorId the value for advice_order.creator_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.province
     *
     * @return the value of advice_order.province
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.province
     *
     * @param province the value for advice_order.province
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.city
     *
     * @return the value of advice_order.city
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.city
     *
     * @param city the value for advice_order.city
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.push_city_id
     *
     * @return the value of advice_order.push_city_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Integer getPushCityId() {
        return pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.push_city_id
     *
     * @param pushCityId the value for advice_order.push_city_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setPushCityId(Integer pushCityId) {
        this.pushCityId = pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.question
     *
     * @return the value of advice_order.question
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.question
     *
     * @param question the value for advice_order.question
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.price
     *
     * @return the value of advice_order.price
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.price
     *
     * @param price the value for advice_order.price
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.order_status
     *
     * @return the value of advice_order.order_status
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.order_status
     *
     * @param orderStatus the value for advice_order.order_status
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.pay_state
     *
     * @return the value of advice_order.pay_state
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.pay_state
     *
     * @param payState the value for advice_order.pay_state
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.create_date
     *
     * @return the value of advice_order.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.create_date
     *
     * @param createDate the value for advice_order.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_order.update_date
     *
     * @return the value of advice_order.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_order.update_date
     *
     * @param updateDate the value for advice_order.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}