package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class BusinessLabelCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label_category.id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label_category.name
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label_category.index_order
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private Byte indexOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label_category.create_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label_category.update_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label_category.id
     *
     * @return the value of business_label_category.id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label_category.id
     *
     * @param id the value for business_label_category.id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label_category.name
     *
     * @return the value of business_label_category.name
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label_category.name
     *
     * @param name the value for business_label_category.name
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label_category.index_order
     *
     * @return the value of business_label_category.index_order
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public Byte getIndexOrder() {
        return indexOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label_category.index_order
     *
     * @param indexOrder the value for business_label_category.index_order
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setIndexOrder(Byte indexOrder) {
        this.indexOrder = indexOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label_category.create_date
     *
     * @return the value of business_label_category.create_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label_category.create_date
     *
     * @param createDate the value for business_label_category.create_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label_category.update_date
     *
     * @return the value of business_label_category.update_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label_category.update_date
     *
     * @param updateDate the value for business_label_category.update_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}