package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class BusinessLabel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label.id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label.name
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label.business_label_category_id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private String businessLabelCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label.index_order
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private Byte indexOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label.create_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label.update_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_label.is_common
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    private Byte isCommon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label.id
     *
     * @return the value of business_label.id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label.id
     *
     * @param id the value for business_label.id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label.name
     *
     * @return the value of business_label.name
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label.name
     *
     * @param name the value for business_label.name
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label.business_label_category_id
     *
     * @return the value of business_label.business_label_category_id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public String getBusinessLabelCategoryId() {
        return businessLabelCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label.business_label_category_id
     *
     * @param businessLabelCategoryId the value for business_label.business_label_category_id
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setBusinessLabelCategoryId(String businessLabelCategoryId) {
        this.businessLabelCategoryId = businessLabelCategoryId == null ? null : businessLabelCategoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label.index_order
     *
     * @return the value of business_label.index_order
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public Byte getIndexOrder() {
        return indexOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label.index_order
     *
     * @param indexOrder the value for business_label.index_order
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setIndexOrder(Byte indexOrder) {
        this.indexOrder = indexOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label.create_date
     *
     * @return the value of business_label.create_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label.create_date
     *
     * @param createDate the value for business_label.create_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label.update_date
     *
     * @return the value of business_label.update_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label.update_date
     *
     * @param updateDate the value for business_label.update_date
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_label.is_common
     *
     * @return the value of business_label.is_common
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public Byte getIsCommon() {
        return isCommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_label.is_common
     *
     * @param isCommon the value for business_label.is_common
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    public void setIsCommon(Byte isCommon) {
        this.isCommon = isCommon;
    }
}