package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class CooperationOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.order_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.creator_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.province
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.city
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.address
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.push_city_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private Integer pushCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.subject_matter_amount
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String subjectMatterAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.business_label
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String businessLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.case_referral_percentage
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String caseReferralPercentage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.detail
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.order_status
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.create_date
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_order.update_date
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.order_id
     *
     * @return the value of cooperation_order.order_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.order_id
     *
     * @param orderId the value for cooperation_order.order_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.creator_id
     *
     * @return the value of cooperation_order.creator_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.creator_id
     *
     * @param creatorId the value for cooperation_order.creator_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.province
     *
     * @return the value of cooperation_order.province
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.province
     *
     * @param province the value for cooperation_order.province
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.city
     *
     * @return the value of cooperation_order.city
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.city
     *
     * @param city the value for cooperation_order.city
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.address
     *
     * @return the value of cooperation_order.address
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.address
     *
     * @param address the value for cooperation_order.address
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.push_city_id
     *
     * @return the value of cooperation_order.push_city_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public Integer getPushCityId() {
        return pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.push_city_id
     *
     * @param pushCityId the value for cooperation_order.push_city_id
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setPushCityId(Integer pushCityId) {
        this.pushCityId = pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.subject_matter_amount
     *
     * @return the value of cooperation_order.subject_matter_amount
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getSubjectMatterAmount() {
        return subjectMatterAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.subject_matter_amount
     *
     * @param subjectMatterAmount the value for cooperation_order.subject_matter_amount
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setSubjectMatterAmount(String subjectMatterAmount) {
        this.subjectMatterAmount = subjectMatterAmount == null ? null : subjectMatterAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.business_label
     *
     * @return the value of cooperation_order.business_label
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getBusinessLabel() {
        return businessLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.business_label
     *
     * @param businessLabel the value for cooperation_order.business_label
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setBusinessLabel(String businessLabel) {
        this.businessLabel = businessLabel == null ? null : businessLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.case_referral_percentage
     *
     * @return the value of cooperation_order.case_referral_percentage
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getCaseReferralPercentage() {
        return caseReferralPercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.case_referral_percentage
     *
     * @param caseReferralPercentage the value for cooperation_order.case_referral_percentage
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setCaseReferralPercentage(String caseReferralPercentage) {
        this.caseReferralPercentage = caseReferralPercentage == null ? null : caseReferralPercentage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.detail
     *
     * @return the value of cooperation_order.detail
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.detail
     *
     * @param detail the value for cooperation_order.detail
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.order_status
     *
     * @return the value of cooperation_order.order_status
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.order_status
     *
     * @param orderStatus the value for cooperation_order.order_status
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.create_date
     *
     * @return the value of cooperation_order.create_date
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.create_date
     *
     * @param createDate the value for cooperation_order.create_date
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cooperation_order.update_date
     *
     * @return the value of cooperation_order.update_date
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cooperation_order.update_date
     *
     * @param updateDate the value for cooperation_order.update_date
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}