package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class LegalOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_order.order_id
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_order.creator_id
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_order.type
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_order.data
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_order.order_status
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_order.create_date
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column legal_order.update_date
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_order.order_id
     *
     * @return the value of legal_order.order_id
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_order.order_id
     *
     * @param orderId the value for legal_order.order_id
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_order.creator_id
     *
     * @return the value of legal_order.creator_id
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_order.creator_id
     *
     * @param creatorId the value for legal_order.creator_id
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_order.type
     *
     * @return the value of legal_order.type
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_order.type
     *
     * @param type the value for legal_order.type
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_order.data
     *
     * @return the value of legal_order.data
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_order.data
     *
     * @param data the value for legal_order.data
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_order.order_status
     *
     * @return the value of legal_order.order_status
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_order.order_status
     *
     * @param orderStatus the value for legal_order.order_status
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_order.create_date
     *
     * @return the value of legal_order.create_date
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_order.create_date
     *
     * @param createDate the value for legal_order.create_date
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column legal_order.update_date
     *
     * @return the value of legal_order.update_date
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column legal_order.update_date
     *
     * @param updateDate the value for legal_order.update_date
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}