package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class OtherOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.order_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.creator_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.province
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.city
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.address
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.push_city_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private Integer pushCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.order_type_description
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String orderTypeDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.intention_price
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String intentionPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.price
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.contact_phone
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.detail
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.order_status
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.pay_state
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private Integer payState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.create_date
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_order.update_date
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.order_id
     *
     * @return the value of other_order.order_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.order_id
     *
     * @param orderId the value for other_order.order_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.creator_id
     *
     * @return the value of other_order.creator_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.creator_id
     *
     * @param creatorId the value for other_order.creator_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.province
     *
     * @return the value of other_order.province
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.province
     *
     * @param province the value for other_order.province
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.city
     *
     * @return the value of other_order.city
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.city
     *
     * @param city the value for other_order.city
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.address
     *
     * @return the value of other_order.address
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.address
     *
     * @param address the value for other_order.address
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.push_city_id
     *
     * @return the value of other_order.push_city_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public Integer getPushCityId() {
        return pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.push_city_id
     *
     * @param pushCityId the value for other_order.push_city_id
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setPushCityId(Integer pushCityId) {
        this.pushCityId = pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.order_type_description
     *
     * @return the value of other_order.order_type_description
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getOrderTypeDescription() {
        return orderTypeDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.order_type_description
     *
     * @param orderTypeDescription the value for other_order.order_type_description
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setOrderTypeDescription(String orderTypeDescription) {
        this.orderTypeDescription = orderTypeDescription == null ? null : orderTypeDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.intention_price
     *
     * @return the value of other_order.intention_price
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getIntentionPrice() {
        return intentionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.intention_price
     *
     * @param intentionPrice the value for other_order.intention_price
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setIntentionPrice(String intentionPrice) {
        this.intentionPrice = intentionPrice == null ? null : intentionPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.price
     *
     * @return the value of other_order.price
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.price
     *
     * @param price the value for other_order.price
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.contact_phone
     *
     * @return the value of other_order.contact_phone
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.contact_phone
     *
     * @param contactPhone the value for other_order.contact_phone
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.detail
     *
     * @return the value of other_order.detail
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.detail
     *
     * @param detail the value for other_order.detail
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.order_status
     *
     * @return the value of other_order.order_status
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.order_status
     *
     * @param orderStatus the value for other_order.order_status
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.pay_state
     *
     * @return the value of other_order.pay_state
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public Integer getPayState() {
        return payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.pay_state
     *
     * @param payState the value for other_order.pay_state
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setPayState(Integer payState) {
        this.payState = payState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.create_date
     *
     * @return the value of other_order.create_date
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.create_date
     *
     * @param createDate the value for other_order.create_date
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_order.update_date
     *
     * @return the value of other_order.update_date
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_order.update_date
     *
     * @param updateDate the value for other_order.update_date
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}