package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class OtherApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_apply.id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_apply.order_id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_apply.applicant_id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    private String applicantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_apply.charge_standard
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    private String chargeStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_apply.apply_state
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    private Integer applyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_apply.create_date
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_apply.update_date
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_apply.id
     *
     * @return the value of other_apply.id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_apply.id
     *
     * @param id the value for other_apply.id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_apply.order_id
     *
     * @return the value of other_apply.order_id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_apply.order_id
     *
     * @param orderId the value for other_apply.order_id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_apply.applicant_id
     *
     * @return the value of other_apply.applicant_id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_apply.applicant_id
     *
     * @param applicantId the value for other_apply.applicant_id
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId == null ? null : applicantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_apply.charge_standard
     *
     * @return the value of other_apply.charge_standard
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public String getChargeStandard() {
        return chargeStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_apply.charge_standard
     *
     * @param chargeStandard the value for other_apply.charge_standard
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public void setChargeStandard(String chargeStandard) {
        this.chargeStandard = chargeStandard == null ? null : chargeStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_apply.apply_state
     *
     * @return the value of other_apply.apply_state
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public Integer getApplyState() {
        return applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_apply.apply_state
     *
     * @param applyState the value for other_apply.apply_state
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public void setApplyState(Integer applyState) {
        this.applyState = applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_apply.create_date
     *
     * @return the value of other_apply.create_date
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_apply.create_date
     *
     * @param createDate the value for other_apply.create_date
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_apply.update_date
     *
     * @return the value of other_apply.update_date
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_apply.update_date
     *
     * @param updateDate the value for other_apply.update_date
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}