package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class Refund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.id
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.out_trade_no
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.out_refund_no
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private String outRefundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.refund_fee
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private Double refundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.refund_description
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private String refundDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.refund_code
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private Integer refundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.error_messages
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private String errorMessages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.result_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private Date resultDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.create_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund.update_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.id
     *
     * @return the value of refund.id
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.id
     *
     * @param id the value for refund.id
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.out_trade_no
     *
     * @return the value of refund.out_trade_no
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.out_trade_no
     *
     * @param outTradeNo the value for refund.out_trade_no
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.out_refund_no
     *
     * @return the value of refund.out_refund_no
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.out_refund_no
     *
     * @param outRefundNo the value for refund.out_refund_no
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.refund_fee
     *
     * @return the value of refund.refund_fee
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public Double getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.refund_fee
     *
     * @param refundFee the value for refund.refund_fee
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setRefundFee(Double refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.refund_description
     *
     * @return the value of refund.refund_description
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public String getRefundDescription() {
        return refundDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.refund_description
     *
     * @param refundDescription the value for refund.refund_description
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setRefundDescription(String refundDescription) {
        this.refundDescription = refundDescription == null ? null : refundDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.refund_code
     *
     * @return the value of refund.refund_code
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public Integer getRefundCode() {
        return refundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.refund_code
     *
     * @param refundCode the value for refund.refund_code
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setRefundCode(Integer refundCode) {
        this.refundCode = refundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.error_messages
     *
     * @return the value of refund.error_messages
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public String getErrorMessages() {
        return errorMessages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.error_messages
     *
     * @param errorMessages the value for refund.error_messages
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setErrorMessages(String errorMessages) {
        this.errorMessages = errorMessages == null ? null : errorMessages.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.result_date
     *
     * @return the value of refund.result_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public Date getResultDate() {
        return resultDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.result_date
     *
     * @param resultDate the value for refund.result_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setResultDate(Date resultDate) {
        this.resultDate = resultDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.create_date
     *
     * @return the value of refund.create_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.create_date
     *
     * @param createDate the value for refund.create_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund.update_date
     *
     * @return the value of refund.update_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund.update_date
     *
     * @param updateDate the value for refund.update_date
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}