package com.wusong.firefly.domain.firefly;

import java.util.Date;

public class UserSubscribe {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subscribe.id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subscribe.user_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subscribe.order_type
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Integer orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subscribe.subscribe_status
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Integer subscribeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subscribe.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_subscribe.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subscribe.id
     *
     * @return the value of user_subscribe.id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subscribe.id
     *
     * @param id the value for user_subscribe.id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subscribe.user_id
     *
     * @return the value of user_subscribe.user_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subscribe.user_id
     *
     * @param userId the value for user_subscribe.user_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subscribe.order_type
     *
     * @return the value of user_subscribe.order_type
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subscribe.order_type
     *
     * @param orderType the value for user_subscribe.order_type
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subscribe.subscribe_status
     *
     * @return the value of user_subscribe.subscribe_status
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Integer getSubscribeStatus() {
        return subscribeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subscribe.subscribe_status
     *
     * @param subscribeStatus the value for user_subscribe.subscribe_status
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setSubscribeStatus(Integer subscribeStatus) {
        this.subscribeStatus = subscribeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subscribe.create_date
     *
     * @return the value of user_subscribe.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subscribe.create_date
     *
     * @param createDate the value for user_subscribe.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_subscribe.update_date
     *
     * @return the value of user_subscribe.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_subscribe.update_date
     *
     * @param updateDate the value for user_subscribe.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}