package com.zeek.athena.domain;

import java.util.Date;

public class AdviceApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply.id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply.order_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply.applicant_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String applicantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply.answer
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply.apply_state
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Integer applyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice_apply.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply.id
     *
     * @return the value of advice_apply.id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply.id
     *
     * @param id the value for advice_apply.id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply.order_id
     *
     * @return the value of advice_apply.order_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply.order_id
     *
     * @param orderId the value for advice_apply.order_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply.applicant_id
     *
     * @return the value of advice_apply.applicant_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply.applicant_id
     *
     * @param applicantId the value for advice_apply.applicant_id
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setApplicantId(String applicantId) {
        this.applicantId = applicantId == null ? null : applicantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply.answer
     *
     * @return the value of advice_apply.answer
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply.answer
     *
     * @param answer the value for advice_apply.answer
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply.apply_state
     *
     * @return the value of advice_apply.apply_state
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Integer getApplyState() {
        return applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply.apply_state
     *
     * @param applyState the value for advice_apply.apply_state
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setApplyState(Integer applyState) {
        this.applyState = applyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply.create_date
     *
     * @return the value of advice_apply.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply.create_date
     *
     * @param createDate the value for advice_apply.create_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice_apply.update_date
     *
     * @return the value of advice_apply.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice_apply.update_date
     *
     * @param updateDate the value for advice_apply.update_date
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}