package com.zeek.athena.domain;

import java.util.Date;

public class EnquiryOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.order_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.creator_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.enquiry_province
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String enquiryProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.enquiry_city
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String enquiryCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.enquiry_address
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String enquiryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.push_city_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private Integer pushCityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.enquiry_type
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String enquiryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.available_material
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String availableMaterial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.contact_name
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.contact_phone
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.detail
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.special_requirements
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String specialRequirements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.order_status
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.reason
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.create_date
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enquiry_order.update_date
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.order_id
     *
     * @return the value of enquiry_order.order_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.order_id
     *
     * @param orderId the value for enquiry_order.order_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.creator_id
     *
     * @return the value of enquiry_order.creator_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.creator_id
     *
     * @param creatorId the value for enquiry_order.creator_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.enquiry_province
     *
     * @return the value of enquiry_order.enquiry_province
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getEnquiryProvince() {
        return enquiryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.enquiry_province
     *
     * @param enquiryProvince the value for enquiry_order.enquiry_province
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setEnquiryProvince(String enquiryProvince) {
        this.enquiryProvince = enquiryProvince == null ? null : enquiryProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.enquiry_city
     *
     * @return the value of enquiry_order.enquiry_city
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getEnquiryCity() {
        return enquiryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.enquiry_city
     *
     * @param enquiryCity the value for enquiry_order.enquiry_city
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setEnquiryCity(String enquiryCity) {
        this.enquiryCity = enquiryCity == null ? null : enquiryCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.enquiry_address
     *
     * @return the value of enquiry_order.enquiry_address
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getEnquiryAddress() {
        return enquiryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.enquiry_address
     *
     * @param enquiryAddress the value for enquiry_order.enquiry_address
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setEnquiryAddress(String enquiryAddress) {
        this.enquiryAddress = enquiryAddress == null ? null : enquiryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.push_city_id
     *
     * @return the value of enquiry_order.push_city_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public Integer getPushCityId() {
        return pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.push_city_id
     *
     * @param pushCityId the value for enquiry_order.push_city_id
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setPushCityId(Integer pushCityId) {
        this.pushCityId = pushCityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.enquiry_type
     *
     * @return the value of enquiry_order.enquiry_type
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getEnquiryType() {
        return enquiryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.enquiry_type
     *
     * @param enquiryType the value for enquiry_order.enquiry_type
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setEnquiryType(String enquiryType) {
        this.enquiryType = enquiryType == null ? null : enquiryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.available_material
     *
     * @return the value of enquiry_order.available_material
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getAvailableMaterial() {
        return availableMaterial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.available_material
     *
     * @param availableMaterial the value for enquiry_order.available_material
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setAvailableMaterial(String availableMaterial) {
        this.availableMaterial = availableMaterial == null ? null : availableMaterial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.contact_name
     *
     * @return the value of enquiry_order.contact_name
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.contact_name
     *
     * @param contactName the value for enquiry_order.contact_name
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.contact_phone
     *
     * @return the value of enquiry_order.contact_phone
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.contact_phone
     *
     * @param contactPhone the value for enquiry_order.contact_phone
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.detail
     *
     * @return the value of enquiry_order.detail
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.detail
     *
     * @param detail the value for enquiry_order.detail
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.special_requirements
     *
     * @return the value of enquiry_order.special_requirements
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getSpecialRequirements() {
        return specialRequirements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.special_requirements
     *
     * @param specialRequirements the value for enquiry_order.special_requirements
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setSpecialRequirements(String specialRequirements) {
        this.specialRequirements = specialRequirements == null ? null : specialRequirements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.order_status
     *
     * @return the value of enquiry_order.order_status
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.order_status
     *
     * @param orderStatus the value for enquiry_order.order_status
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.reason
     *
     * @return the value of enquiry_order.reason
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.reason
     *
     * @param reason the value for enquiry_order.reason
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.create_date
     *
     * @return the value of enquiry_order.create_date
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.create_date
     *
     * @param createDate the value for enquiry_order.create_date
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enquiry_order.update_date
     *
     * @return the value of enquiry_order.update_date
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enquiry_order.update_date
     *
     * @param updateDate the value for enquiry_order.update_date
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}