package com.zeek.athena.dao;

import com.zeek.athena.domain.BlackList;

public interface BlackListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int insert(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int insertSelective(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    BlackList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int updateByPrimaryKeySelective(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int updateByPrimaryKey(BlackList record);
}