package com.zeek.athena.dao;

import com.zeek.athena.domain.EnquiryOrder;

public interface EnquiryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Tue May 23 21:19:12 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Tue May 23 21:19:12 CST 2017
     */
    int insert(EnquiryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Tue May 23 21:19:12 CST 2017
     */
    int insertSelective(EnquiryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Tue May 23 21:19:12 CST 2017
     */
    EnquiryOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Tue May 23 21:19:12 CST 2017
     */
    int updateByPrimaryKeySelective(EnquiryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Tue May 23 21:19:12 CST 2017
     */
    int updateByPrimaryKey(EnquiryOrder record);
}