package com.zeek.athena.dao;

import com.zeek.athena.domain.MessagePublishTask;

public interface MessagePublishTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_publish_task
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_publish_task
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int insert(MessagePublishTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_publish_task
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int insertSelective(MessagePublishTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_publish_task
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    MessagePublishTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_publish_task
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int updateByPrimaryKeySelective(MessagePublishTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_publish_task
     *
     * @mbggenerated Fri Jun 02 17:10:40 CST 2017
     */
    int updateByPrimaryKey(MessagePublishTask record);
}