package com.zeek.athena.dao;

import com.zeek.athena.domain.UserSubscribe;

public interface UserSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Sat May 27 14:39:11 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Sat May 27 14:39:11 CST 2017
     */
    int insert(UserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Sat May 27 14:39:11 CST 2017
     */
    int insertSelective(UserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Sat May 27 14:39:11 CST 2017
     */
    UserSubscribe selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Sat May 27 14:39:11 CST 2017
     */
    int updateByPrimaryKeySelective(UserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Sat May 27 14:39:11 CST 2017
     */
    int updateByPrimaryKey(UserSubscribe record);
}