package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.AdviceApplyLike;

public interface AdviceApplyLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_like
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_like
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int insert(AdviceApplyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_like
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int insertSelective(AdviceApplyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_like
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    AdviceApplyLike selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_like
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int updateByPrimaryKeySelective(AdviceApplyLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_like
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int updateByPrimaryKey(AdviceApplyLike record);
}