package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.AdviceApply;

public interface AdviceApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insert(AdviceApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insertSelective(AdviceApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    AdviceApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKeySelective(AdviceApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKey(AdviceApply record);
}