package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.AdviceApplySupplement;

public interface AdviceApplySupplementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_supplement
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_supplement
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int insert(AdviceApplySupplement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_supplement
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int insertSelective(AdviceApplySupplement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_supplement
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    AdviceApplySupplement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_supplement
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int updateByPrimaryKeySelective(AdviceApplySupplement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice_apply_supplement
     *
     * @mbggenerated Thu Nov 09 10:18:40 CST 2017
     */
    int updateByPrimaryKey(AdviceApplySupplement record);
}