package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.BlackList;

public interface BlackListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insert(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insertSelective(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    BlackList selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKeySelective(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKey(BlackList record);
}