package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.BusinessLabel;

public interface BusinessLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int insert(BusinessLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int insertSelective(BusinessLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    BusinessLabel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int updateByPrimaryKeySelective(BusinessLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int updateByPrimaryKey(BusinessLabel record);
}