package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.BusinessLabelCategory;

public interface BusinessLabelCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label_category
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label_category
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int insert(BusinessLabelCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label_category
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int insertSelective(BusinessLabelCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label_category
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    BusinessLabelCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label_category
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int updateByPrimaryKeySelective(BusinessLabelCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_label_category
     *
     * @mbggenerated Thu Jun 22 17:33:33 CST 2017
     */
    int updateByPrimaryKey(BusinessLabelCategory record);
}