package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.CooperationApply;

public interface CooperationApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperation_apply
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperation_apply
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    int insert(CooperationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperation_apply
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    int insertSelective(CooperationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperation_apply
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    CooperationApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperation_apply
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    int updateByPrimaryKeySelective(CooperationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cooperation_apply
     *
     * @mbggenerated Mon Jun 19 18:48:23 CST 2017
     */
    int updateByPrimaryKey(CooperationApply record);
}