package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.EnquiryOrder;

public interface EnquiryOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insert(EnquiryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insertSelective(EnquiryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    EnquiryOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKeySelective(EnquiryOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enquiry_order
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKey(EnquiryOrder record);
}