package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.LegalOrder;

public interface LegalOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_order
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_order
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    int insert(LegalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_order
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    int insertSelective(LegalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_order
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    LegalOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_order
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    int updateByPrimaryKeySelective(LegalOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table legal_order
     *
     * @mbggenerated Mon Jun 26 16:58:13 CST 2017
     */
    int updateByPrimaryKey(LegalOrder record);
}