package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.OtherOrder;

public interface OtherOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_order
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_order
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    int insert(OtherOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_order
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    int insertSelective(OtherOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_order
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    OtherOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_order
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    int updateByPrimaryKeySelective(OtherOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_order
     *
     * @mbggenerated Mon Jun 26 18:48:51 CST 2017
     */
    int updateByPrimaryKey(OtherOrder record);
}