package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.OtherApply;

public interface OtherApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_apply
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_apply
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    int insert(OtherApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_apply
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    int insertSelective(OtherApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_apply
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    OtherApply selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_apply
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    int updateByPrimaryKeySelective(OtherApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_apply
     *
     * @mbggenerated Mon Jun 26 18:56:29 CST 2017
     */
    int updateByPrimaryKey(OtherApply record);
}