package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.Refund;

public interface RefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    int insert(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    int insertSelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    Refund selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    int updateByPrimaryKeySelective(Refund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund
     *
     * @mbggenerated Wed Aug 02 19:47:10 CST 2017
     */
    int updateByPrimaryKey(Refund record);
}