package com.wusong.firefly.dao.mysql.firefly;

import com.wusong.firefly.domain.firefly.UserSubscribe;

public interface UserSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insert(UserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int insertSelective(UserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    UserSubscribe selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKeySelective(UserSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_subscribe
     *
     * @mbggenerated Mon Jun 12 17:13:23 CST 2017
     */
    int updateByPrimaryKey(UserSubscribe record);
}