package com.wusong.hanukkah.domain.mysql;

import java.util.Date;

public class UserWusongCourseCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wusong_course_code.id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wusong_course_code.user_id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wusong_course_code.wusong_course_id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    private String wusongCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wusong_course_code.code
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wusong_course_code.invitation_url
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    private String invitationUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wusong_course_code.create_date
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wusong_course_code.id
     *
     * @return the value of user_wusong_course_code.id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wusong_course_code.id
     *
     * @param id the value for user_wusong_course_code.id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wusong_course_code.user_id
     *
     * @return the value of user_wusong_course_code.user_id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wusong_course_code.user_id
     *
     * @param userId the value for user_wusong_course_code.user_id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wusong_course_code.wusong_course_id
     *
     * @return the value of user_wusong_course_code.wusong_course_id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public String getWusongCourseId() {
        return wusongCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wusong_course_code.wusong_course_id
     *
     * @param wusongCourseId the value for user_wusong_course_code.wusong_course_id
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public void setWusongCourseId(String wusongCourseId) {
        this.wusongCourseId = wusongCourseId == null ? null : wusongCourseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wusong_course_code.code
     *
     * @return the value of user_wusong_course_code.code
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wusong_course_code.code
     *
     * @param code the value for user_wusong_course_code.code
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wusong_course_code.invitation_url
     *
     * @return the value of user_wusong_course_code.invitation_url
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public String getInvitationUrl() {
        return invitationUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wusong_course_code.invitation_url
     *
     * @param invitationUrl the value for user_wusong_course_code.invitation_url
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public void setInvitationUrl(String invitationUrl) {
        this.invitationUrl = invitationUrl == null ? null : invitationUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wusong_course_code.create_date
     *
     * @return the value of user_wusong_course_code.create_date
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wusong_course_code.create_date
     *
     * @param createDate the value for user_wusong_course_code.create_date
     *
     * @mbggenerated Thu Nov 09 10:14:14 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}