package com.wusong.hanukkah.domain.mysql;

import java.util.Date;

public class WusongCourseCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course_code.id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course_code.wusong_course_id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private String wusongCourseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course_code.code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course_code.status
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course_code.create_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course_code.modify_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course_code.id
     *
     * @return the value of wusong_course_code.id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course_code.id
     *
     * @param id the value for wusong_course_code.id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course_code.wusong_course_id
     *
     * @return the value of wusong_course_code.wusong_course_id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public String getWusongCourseId() {
        return wusongCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course_code.wusong_course_id
     *
     * @param wusongCourseId the value for wusong_course_code.wusong_course_id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setWusongCourseId(String wusongCourseId) {
        this.wusongCourseId = wusongCourseId == null ? null : wusongCourseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course_code.code
     *
     * @return the value of wusong_course_code.code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course_code.code
     *
     * @param code the value for wusong_course_code.code
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course_code.status
     *
     * @return the value of wusong_course_code.status
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course_code.status
     *
     * @param status the value for wusong_course_code.status
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course_code.create_date
     *
     * @return the value of wusong_course_code.create_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course_code.create_date
     *
     * @param createDate the value for wusong_course_code.create_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course_code.modify_date
     *
     * @return the value of wusong_course_code.modify_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course_code.modify_date
     *
     * @param modifyDate the value for wusong_course_code.modify_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}