package com.wusong.hanukkah.domain.mysql;

import java.util.Date;

public class WusongCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.title
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.lecturer
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private String lecturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.course_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Date courseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.price
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.picture_url
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.type
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.create_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wusong_course.modify_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    private Date modifyDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.id
     *
     * @return the value of wusong_course.id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.id
     *
     * @param id the value for wusong_course.id
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.title
     *
     * @return the value of wusong_course.title
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.title
     *
     * @param title the value for wusong_course.title
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.lecturer
     *
     * @return the value of wusong_course.lecturer
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public String getLecturer() {
        return lecturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.lecturer
     *
     * @param lecturer the value for wusong_course.lecturer
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setLecturer(String lecturer) {
        this.lecturer = lecturer == null ? null : lecturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.course_date
     *
     * @return the value of wusong_course.course_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Date getCourseDate() {
        return courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.course_date
     *
     * @param courseDate the value for wusong_course.course_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setCourseDate(Date courseDate) {
        this.courseDate = courseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.price
     *
     * @return the value of wusong_course.price
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.price
     *
     * @param price the value for wusong_course.price
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.picture_url
     *
     * @return the value of wusong_course.picture_url
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.picture_url
     *
     * @param pictureUrl the value for wusong_course.picture_url
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.type
     *
     * @return the value of wusong_course.type
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.type
     *
     * @param type the value for wusong_course.type
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.create_date
     *
     * @return the value of wusong_course.create_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.create_date
     *
     * @param createDate the value for wusong_course.create_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wusong_course.modify_date
     *
     * @return the value of wusong_course.modify_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wusong_course.modify_date
     *
     * @param modifyDate the value for wusong_course.modify_date
     *
     * @mbggenerated Mon Sep 11 11:20:42 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}